# Generated by Django 4.2.2 on 2023-07-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="privacy",
            field=models.BooleanField(default=False),
        ),
    ]
