# Generated by Django 4.2.2 on 2023-07-06 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("likes", "0002_initial"),
        ("posts", "0003_post_privacy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="like",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes_post",
                to="likes.like",
            ),
        ),
    ]
