# Generated by Django 4.2.2 on 2023-07-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfollower",
            name="is_friend",
            field=models.BooleanField(default=False),
        ),
    ]
